### PR TITLE
add runner.sh

### PR DESCRIPTION
**Pull request by aeromomo**
It wiil not work unless you are in TT

### CODE REVIEW

**Comment by usuket** [comment]
Hm... I think this runner should not be managed by git.
because this script will break directory such as additional and config.
** also It might break my local test environment **

If you want to manage the runner script, an additional file, and a customized config.
Probably It is a good idea that creates new private git for managing those scripts then
calls generate_iso.sh from the outer directory.  

It looks good idea to me.
```
variable=ubuntu_$(date +%y%m%d-%H-%M).iso
```

But at least this path should be passed by params
bash runner.sh "~/ttpub/Download/isos/$variable"
```
the_path=$1
mv customized_ubuntu.iso $variable
```

**Comment by usuket** [comment]
Of course, I can merge this script, but it seems that a little bit modifies needed.

**Comment by aeromomo** [comment]
it's okay, i can keep it local

**Comment by usuket** [comment]
thank you for your understanding.

**Pull request closed without merging**
